### ISSUE TITLE
Source build fails on new ubuntu instance

### ISSUE THREAD

**Issue by alex-hancock** [CancerCollaboratory/sandbox#151]
I'm having errors building the Consonance source, so I tried it on a fresh AWS Ubuntu instance, and it still fails. What's going wrong?

1. Create a new Ubuntu 16.04 instance on AWS
2. Run `git clone https://github.com/Consonance/consonance.git`
    a) Fetch tags and switched to 2.0.0-alpha.15
3. Install java-8-openjdk (using the command `sudo apt-get install openjdk-8-jdk`)
4. Set JAVA_HOME and PATH
    a) `export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre`
    b) `export PATH=$PATH:$JAVA_HOME/bin`
    c) Check with `javac -version`
5. Install maven using `sudo apt install maven`
    a) Check with `mvn -v`
6. Run `mvn clean install` in the cloned repo

This failure occurs during the consonance-reporting section of the build:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.consonance.common.Arch3ReportImplTest
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.551 sec <<< FAILURE! - in io.consonance.common.Arch3ReportImplTest
testGetJobInfo(io.consonance.common.Arch3ReportImplTest)  Time elapsed: 0.489 sec  <<< ERROR!
java.lang.RuntimeException: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)
Caused by: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)

testGetJobStateCounts(io.consonance.common.Arch3ReportImplTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.RuntimeException: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)
Caused by: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)

testGetCommands(io.consonance.common.Arch3ReportImplTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.RuntimeException: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)
Caused by: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)

testSlackRendering(io.consonance.common.Arch3ReportImplTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.RuntimeException: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)
Caused by: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)

testGetVMStateCounts(io.consonance.common.Arch3ReportImplTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.RuntimeException: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)
Caused by: java.sql.SQLException: invalid database address: jdbc:postgresql://127.0.0.1/queue_status
	at io.consonance.common.Arch3ReportImplTest.setup(Arch3ReportImplTest.java:55)


Results :

Tests in error: 
  Arch3ReportImplTest.setup:55 » Runtime java.sql.SQLException: invalid database...
  Arch3ReportImplTest.setup:55 » Runtime java.sql.SQLException: invalid database...
  Arch3ReportImplTest.setup:55 » Runtime java.sql.SQLException: invalid database...
  Arch3ReportImplTest.setup:55 » Runtime java.sql.SQLException: invalid database...
  Arch3ReportImplTest.setup:55 » Runtime java.sql.SQLException: invalid database...

Tests run: 5, Failures: 0, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] consonance ......................................... SUCCESS [  4.165 s]
[INFO] consonance-common .................................. SUCCESS [  8.577 s]
[INFO] consonance-server-common ........................... SUCCESS [  8.516 s]
[INFO] consonance-arch .................................... SUCCESS [ 32.827 s]
[INFO] consonance-reporting ............................... FAILURE [  3.088 s]
[INFO] consonance-webservice .............................. SKIPPED
[INFO] swagger-java-client ................................ SKIPPED
[INFO] consonance-client .................................. SKIPPED
[INFO] consonance-integration-testing ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.556 s
[INFO] Finished at: 2017-08-22T20:19:16+00:00
[INFO] Final Memory: 80M/820M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project consonance-reporting: There are test failures.
```

For some reason, the test failures are also included when running `mvn -Daven.test.skip=true clean install`, so I am unable to get past the build failures. What's going wrong?

**Comment by SolomonShorser-OICR** [comment]
Should there be an `m` in `mvn -Daven.test.skip=true clean install` as in: `mvn -Dmaven.test.skip=true clean install`? What about `-DskipTests` or `-DskipTests=true`?

**Comment by alex-hancock** [comment]
The 2.0.0-alpha.15 README has `-Dmaven` and the current develop README has `-Daven`, but neither works. `mvn -Dmaven.test.skip=true clean install` fails even earlier:
```
[INFO] --- maven-dependency-plugin:2.10:analyze-only (analyze) @ consonance-arch ---
[WARNING] Unused declared dependencies found:
[WARNING]    ch.qos.logback:logback-classic:jar:1.1.7:compile
[WARNING]    commons-dbutils:commons-dbutils:jar:1.6:compile
[WARNING]    ch.qos.logback:logback-core:jar:1.1.7:compile
[WARNING]    com.google.guava:guava:jar:19.0:compile
[WARNING]    org.apache.commons:commons-dbcp2:jar:2.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] consonance ......................................... SUCCESS [  4.053 s]
[INFO] consonance-common .................................. SUCCESS [  8.191 s]
[INFO] consonance-server-common ........................... SUCCESS [  8.456 s]
[INFO] consonance-arch .................................... FAILURE [ 16.504 s]
[INFO] consonance-reporting ............................... SKIPPED
[INFO] consonance-webservice .............................. SKIPPED
[INFO] swagger-java-client ................................ SKIPPED
[INFO] consonance-client .................................. SKIPPED
[INFO] consonance-integration-testing ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.568 s
[INFO] Finished at: 2017-08-22T21:35:52+00:00
[INFO] Final Memory: 66M/812M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze-only (analyze) on project consonance-arch: Dependency problems found -> [Help 1]
```

Both `-DskipTests` and `-DskipTests=true` work fine, so the README should be adjusted accordingly, thank you. 

On the other hand, why are tests failing on a static release of Consonance? And if I'm missing some dependency, what is it?

**Comment by SolomonShorser-OICR** [comment]
`-Daven` certainly looks like a typo, thanks for catching that! :)

Judging by the error message `invalid database address: jdbc:postgresql://127.0.0.1/queue_status`, I would imagine that the test in question requires a valid database to be available. So either the database is not running, or if it is running, the code in the test is unable to connect to it.

If you want to run the test, you can set up a Postgres database, using the schema found here: https://github.com/Consonance/consonance/blob/develop/consonance-arch/sql/schema.sql

**Comment by denis-yuen** [comment]
This is probably too late but the two issues seem unrelated. 
The first issue refers to a database being unavailable (maybe travis-ci has postgres available) but maybe you're running locally without postgres. 

The second issue is a maven plugin that limits the size of built artifacts by not allowing you to include dependencies that you don't use.
