### ISSUE TITLE
When the openstack metadata interface is unavailable, just retry indefinitely

### ISSUE THREAD

**Issue by denis-yuen** [CancerCollaboratory/sandbox#48]
```
[WORKER] ubuntu@regionOne-06482408-b95c-4c91-acb6-efdff3a12b38:~$ cat arch3.log 
2015-07-08 19:39:57.187 [main] INFO  i.p.arch3.worker.WorkerRunnable -  WORKER VM UUID provided as: 'null'
2015-07-08 19:39:59.029 [main] ERROR i.p.arch3.worker.WorkerRunnable - Could not determine cloud id
java.lang.RuntimeException: Could not determine cloud id
        at info.pancancer.arch3.worker.WorkerRunnable.run(WorkerRunnable.java:151) ~[pancancer-arch-3-1.1-beta.3.jar:1.1-beta.3]
        at info.pancancer.arch3.worker.Worker.main(Worker.java:65) ~[pancancer-arch-3-1.1-beta.3.jar:1.1-beta.3]
2015-07-08 19:39:59.030 [main] INFO  info.pancancer.arch3.worker.Worker - Exiting.
2015-07-08 19:39:59.033 [Thread-0] INFO  info.pancancer.arch3.worker.Worker - Worker caught a shutdown signal, shutting down now!
2015-07-08 19:39:59.057 [Thread-0] ERROR info.pancancer.arch3.worker.Worker - Unable to delete PID file: /var/run/arch3_worker.pid , message: /var/run/arch3_worker.pid
2015-07-08 19:39:59.057 [Thread-0] ERROR info.pancancer.arch3.worker.Worker - You may have to delete the PID file manually to run the worker again.
```

**Comment by denis-yuen** [comment]
As a stopgap solution, just retry indefinitely

**Comment by denis-yuen** [comment]
Or not
